name:                funcnet
version:             0.1.0.0
github:              "StefanStegmueller/funcnet"
license:             BSD3
author:              "Stefan Stegmueller"
maintainer:          "Stefan.Steg@gmail.com"
copyright:           "2020 Stefan Stegmueller"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/StefanStegmueller/funcnet#readme>

dependencies:
- base >= 4.7 && < 5
- lens == 4.19.2
- normaldistribution == 1.1.0.3
- split == 0.2.3.4

library:
  source-dirs: src

executables:
  funcnet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funcnet 
  simplenn-exe:
    main:                SimpleNN.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is SimpleNN
    dependencies:
    - funcnet 

tests:
  funcnet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funcnet 
    - hspec
